### ISSUE TITLE
Persistence on creation of user ivanjericevich on local deployment

### ISSUE THREAD

**Issue by mgrazianoc** [dharmeshsing/CoinTossX#5]
### System: 
Fedora 34

### Expected Behaviour
Creation of folders according to the `SOFTWARE_PATH` variable;

### Actual Behaviour
Persistence on creation of user ivanjericevich on home directory;

### Steps to reproduce
The same on `README.md`, error arrises on step `./gradlew -Penv=local clean installDist bootWar copyResourcesToInstallDir copyToDeploy deployLocal`

### Important configurations and logs
`SOFTWARE_PATH=/home/marco/[...]/software`
`DATA_PATH=/home/marco/[...]/software/data`

```
> Task :deployLocal FAILED
Clean Software directory ...
Copy files to server...

FAILURE: Build failed with an exception.

* Where:
Script '/home/marco/[...]/CoinTossX/deploy_local.gradle' line: 18

* What went wrong:
Execution failed for task ':deployLocal'.
> Could not copy file '/home/marco/[...]/CoinTossX/deploy/scripts' to '/home/ivanjericevich/run/scripts'.
   > Failed to create parent directory '/home/ivanjericevich' when creating directory '/home/ivanjericevich/run/scripts'
```

The error arises for the reason that the user does not belongs to the user group with permission to write on ivanjericevich.

Running on sudo, the folders are created inside ivanjericevich, but as one expect it, the program will just not work this way.

**Comment by IvanJericevich** [comment]
Thanks for bringing this up, very helpful. I think this this is fixed now. The `SOFTWARE_PATH` had been wrongly specified in the `build.gradle` file.

It should work by following the same process you had above with

`SOFTWARE_PATH=/home/marco/[...]/software`
`DATA_PATH=/home/marco/[...]/software/data`

and then running

`./gradlew -Penv=local build -x test`
`./gradlew -Penv=local clean installDist bootWar copyResourcesToInstallDir copyToDeploy deployLocal`

**Comment by mgrazianoc** [comment]
Issue fixed. Thanks!
